---
title: "Supporting information"
author: "Thomas Ellis, Froukje Postma, Christopher Oakley and Jon Ågren"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  pdf_document:
    toc: true
  bookdown::pdf_book:
    toc: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, fig.pos = 'H', eval=T)
library("qtl", quietly = T)
library("arghqtl")
library("knitr")
```

```{r import-data, eval=T, include=FALSE}
source("R/parents.R")
# get the differences between parental means in each expeirment.
parent_diffs <- data.frame(
  it2010 = parents$delta[parents$site == "italy"  & parents$year == "2010"],
  it2011 = parents$delta[parents$site == "italy"  & parents$year == "2011"],
  sw2010 = parents$delta[parents$site == "sweden" & parents$year == "2010"],
  sw2011 = parents$delta[parents$site == "sweden" & parents$year == "2011"])
parent_diffs <- parent_diffs[c(1,3,2,6,4,7,5),]
parent_diffs$trait <- c("mass", "seed", "frut", "ffit", "surv", "tofu", "tfit")[c(1,3,2,6,4,7,5)]

# import QTL data
cross       <- readRDS(file='output/cross_objects.rds')
qtlmodels   <- readRDS(file='output/qtl_stepwise_models.rds')
qtlfits     <- readRDS(file='output/qtl_model_fits.rds')
qtlclusters <- readRDS(file='output/qtl_clusters.rds')

# Heritability estimates and confidence intervals
H2 <- readRDS("output/heritabilities.rds")

# Traits to be presented.
traits <- c("mass","seed", "tofu", "tfit")

site_names  <- c("Italy", "Italy", "Sweden", "Sweden")
year_names  <- c(2010, 2011, 2010, 2011)
```

This document contains supporting tables and figures for the manuscript "Positive correlations among fitness components boost estimates of local adaptation in *Arabidopsis thaliana*" by Thomas Ellis, Froukje Postma, Christopher Oakley and Jon Ågren.

```{r tab:individual-seed-qtl, eval=T}
# seed number per fruit
ix <- "seed"
tab <- list(bayesint_table(qtlmodels[[ix]]$it2010, qtlfits[[ix]]$it2010),
            bayesint_table(qtlmodels[[ix]]$it2011, qtlfits[[ix]]$it2011),
            bayesint_table(qtlmodels[[ix]]$sw2010, qtlfits[[ix]]$sw2010),
            bayesint_table(qtlmodels[[ix]]$sw2011, qtlfits[[ix]]$sw2011))

for(i in 1:4){
  tab[[i]]$site <- rep(site_names[i], nrow(tab[[i]])) # add experiment names
  tab[[i]]$year <- rep(year_names[i], nrow(tab[[i]])) # add experiment names
  #tab[[i]]$PDE <- 100*abs(tab[[i]]$effect_sizes) / parent_diffs[parent_diffs$trait == ix, i]
}
tab <- do.call('rbind', tab)
# mash together positions with their CIs
tab$position <- paste(round(tab$ML_bayesint,1),
                      " (", round(tab$min_bayesint, 1), "-", round(tab$max_bayesint, 1), ")", sep="")
# print the table
kable(tab[,c("name", "site", "year","chr","position","LOD", "effect_sizes","PVE")],#, "PDE")],
      digits = c(0,0,0,0,0,1,3,1,1),
      col.names = c("Name", "Site", "Year","Chr.","Position (cM)","LOD", "Effect size","% var. explained"),# "% diff. explained"),
      caption="QTL for seed number per fruit identifed in individual experiments. QTL positions are shown with their 95% Bayesian credible intervals. Effect sizes are given as absolute values and as a percentage of variance among RIL means.")
```

\newpage

```{r tab:individual-tofu-qtl, eval=T}
# total fecundity
ix <- "tofu"
tab <- list(bayesint_table(qtlmodels[[ix]]$it2010, qtlfits[[ix]]$it2010),
            bayesint_table(qtlmodels[[ix]]$it2011, qtlfits[[ix]]$it2011),
            bayesint_table(qtlmodels[[ix]]$sw2010, qtlfits[[ix]]$sw2010),
            bayesint_table(qtlmodels[[ix]]$sw2011, qtlfits[[ix]]$sw2011))

for(i in 1:4){
  tab[[i]]$site <- rep(site_names[i], nrow(tab[[i]])) # add experiment names
  tab[[i]]$year <- rep(year_names[i], nrow(tab[[i]])) # add experiment names
  #tab[[i]]$PDE <- 100*abs(tab[[i]]$effect_sizes) / parent_diffs[parent_diffs$trait == ix, i]
}
tab <- do.call('rbind', tab)
# mash together positions with their CIs
tab$position <- paste(round(tab$ML_bayesint,1),
                      " (", round(tab$min_bayesint, 1), "-", round(tab$max_bayesint, 1), ")", sep="")
# print the table
kable(tab[,c("name", "site", "year","chr","position","LOD", "effect_sizes","PVE")],#, "PDE")],
      digits = c(0,0,0,0,0,1,3,1,1),
      col.names = c("Name", "Site", "Year","Chr.","Position (cM)","LOD", "Effect size","% var. explained"),# "% diff. explained"),
      caption = "QTL for seed number per reproductive plant identifed in individual experiments. QTL positions are shown with their 95% Bayesian credible intervals. Effect sizes are given as absolute values and as a percentage of variance among RIL means.")

```

\newpage

```{r tab:individual-tfit-qtl, eval=T}
# seeds/seedling
ix <- "tfit"
tab <- list(bayesint_table(qtlmodels[[ix]]$it2010, qtlfits[[ix]]$it2010),
            bayesint_table(qtlmodels[[ix]]$it2011, qtlfits[[ix]]$it2011),
            bayesint_table(qtlmodels[[ix]]$sw2010, qtlfits[[ix]]$sw2010),
            bayesint_table(qtlmodels[[ix]]$sw2011, qtlfits[[ix]]$sw2011))

for(i in 1:4){
  tab[[i]]$site <- rep(site_names[i], nrow(tab[[i]])) # add experiment names
  tab[[i]]$year <- rep(year_names[i], nrow(tab[[i]])) # add experiment names
  #tab[[i]]$PDE <- 100*abs(tab[[i]]$effect_sizes) / parent_diffs[parent_diffs$trait == ix, i]
}
tab <- do.call('rbind', tab)
# mash together positions with their CIs
tab$position <- paste(round(tab$ML_bayesint,1),
                      " (", round(tab$min_bayesint, 1), "-", round(tab$max_bayesint, 1), ")", sep="")
# print the table
kable(tab[,c("name", "site", "year","chr","position","LOD", "effect_sizes","PVE")],#, "PDE")],
      digits = c(0,0,0,0,0,1,3,1,1),
      col.names = c("Name", "Site", "Year","Chr.","Position (cM)","LOD", "Effect size","% var. explained"),# "% diff. explained"),
      caption = "QTL for seed number per planted seedling identifed in individual experiments. QTL positions are shown with their 95% Bayesian credible intervals. Effect sizes are given as absolute values and as a percentage of variance among RIL means.")

```

\newpage

```{r tab:individual-mass-qtl, eval=T}
# summary tables for each experiment
ix <- "mass"


tab <- list(bayesint_table(qtlmodels[[ix]]$it2010, qtlfits[[ix]]$it2010),
            bayesint_table(qtlmodels[[ix]]$it2011, qtlfits[[ix]]$it2011),
            bayesint_table(qtlmodels[[ix]]$sw2010, qtlfits[[ix]]$sw2010),
            bayesint_table(qtlmodels[[ix]]$sw2011, qtlfits[[ix]]$sw2011))

for(i in 1:4){
  tab[[i]]$site <- rep(site_names[i], nrow(tab[[i]])) # add experiment names
  tab[[i]]$year <- rep(year_names[i], nrow(tab[[i]])) # add experiment names
  #tab[[i]]$PDE <- 100*abs(tab[[i]]$effect_sizes) / parent_diffs[parent_diffs$trait == ix, i]
}
tab <- do.call('rbind', tab)
# mash together positions with their CIs
tab$position <- paste(round(tab$ML_bayesint,1),
                      " (", round(tab$min_bayesint, 1), "-", round(tab$max_bayesint, 1), ")", sep="")
# print the table
kable(tab[,c("name", "site", "year","chr","position","LOD", "effect_sizes","PVE")],#, "PDE")],
      digits = c(0,0,0,0,0,1,3,1,1),
      col.names = c("Name", "Site", "Year","Chr.","Position (cM)","LOD", "Effect size","% var. explained"),# "% diff. explained"),
      caption="QTL for seed mass identifed in individual experiments. QTL positions are shown with their 95% Bayesian credible intervals. Effect sizes are given as absolute values and as a percentage of variance among RIL means.")
```

\newpage

```{r tab:individual-frut-qtl, eval=F}
# summary tables for fruits/plant
ix <- "frut"
tab <- list(bayesint_table(qtlmodels[[ix]]$it2010, qtlfits[[ix]]$it2010),
            bayesint_table(qtlmodels[[ix]]$it2011, qtlfits[[ix]]$it2011),
            bayesint_table(qtlmodels[[ix]]$sw2010, qtlfits[[ix]]$sw2010),
            bayesint_table(qtlmodels[[ix]]$sw2011, qtlfits[[ix]]$sw2011))

for(i in 1:4){
  tab[[i]]$site <- rep(site_names[i], nrow(tab[[i]])) # add experiment names
  tab[[i]]$year <- rep(year_names[i], nrow(tab[[i]])) # add experiment names
  #tab[[i]]$PDE <- 100*abs(tab[[i]]$effect_sizes) / parent_diffs[parent_diffs$trait == ix, i]
}
tab <- do.call('rbind', tab)
# mash together positions with their CIs
tab$position <- paste(round(tab$ML_bayesint,1),
                      " (", round(tab$min_bayesint, 1), "-", round(tab$max_bayesint, 1), ")", sep="")
# print the table
kable(tab[,c("name", "site", "year","chr","position","LOD", "effect_sizes","PVE")],#, "PDE")],
      digits = c(0,0,0,0,0,1,3,1,1),
      col.names = c("Name", "Site", "Year","Chr.","Position (cM)","LOD", "Effect size","% var. explained"),# "% diff. explained"),
      caption="QTL for fruit number per reproductive plant identifed in individual experiments. QTL positions are shown with their 95% Bayesian credible intervals. Effect sizes are given as absolute values and as a percentage of variance among RIL means.")
```

\newpage

```{r tab:individual-ffit-qtl, eval=F}
# Fruit number per seedling
ix <- "ffit"
tab <- list(bayesint_table(qtlmodels[[ix]]$it2010, qtlfits[[ix]]$it2010),
            bayesint_table(qtlmodels[[ix]]$it2011, qtlfits[[ix]]$it2011),
            bayesint_table(qtlmodels[[ix]]$sw2010, qtlfits[[ix]]$sw2010),
            bayesint_table(qtlmodels[[ix]]$sw2011, qtlfits[[ix]]$sw2011))

for(i in 1:4){
  tab[[i]]$site <- rep(site_names[i], nrow(tab[[i]])) # add experiment names
  tab[[i]]$year <- rep(year_names[i], nrow(tab[[i]])) # add experiment names
  tab[[i]]$PDE <- 100*abs(tab[[i]]$effect_sizes) / parent_diffs[parent_diffs$trait == ix, i]
}
tab <- do.call('rbind', tab)
# mash together positions with their CIs
tab$position <- paste(round(tab$ML_bayesint,1),
                      " (", round(tab$min_bayesint, 1), "-", round(tab$max_bayesint, 1), ")", sep="")
# print the table
kable(tab[,c("name", "site", "year","chr","position","LOD", "effect_sizes","PVE", "PDE")], digits = c(0,0,0,0,0,1,3,1,1),
      col.names = c("Name", "Site", "Year","Chr.","Position (cM)","LOD", "Effect size","% var. explained", "% diff. explained"),
      caption = "QTL for fruit number per planted seedling identifed in individual experiments. QTL positions are shown with their 95% Bayesian credible intervals. Effect sizes are given as absolute values, as a percentage of variance among RIL means, and as a percentage of the difference between parental means.")

```

\newpage

```{r tab:individual-surv-qtl, eval=F}
# survival to reproduction
site_names  <- c("Italy", "Italy", "Sweden")
year_names  <- c(2010, 2011, 2011)


ix <- "surv"
tab <- list(bayesint_table(qtlmodels[[ix]]$it2010, qtlfits[[ix]]$it2010),
            bayesint_table(qtlmodels[[ix]]$it2011, qtlfits[[ix]]$it2011),
            #bayesint_table(qtlmodels[[ix]]$sw2010, qtlfits[[ix]]$sw2010),
            bayesint_table(qtlmodels[[ix]]$sw2011, qtlfits[[ix]]$sw2011))

pd <- parent_diffs[parent_diffs$trait == ix,c(1,2,4)]

for(i in 1:3){
  tab[[i]]$site <- rep(site_names[i], nrow(tab[[i]])) # add experiment names
  tab[[i]]$year <- rep(year_names[i], nrow(tab[[i]])) # add experiment names
  tab[[i]]$PDE <- (100* abs(tab[[i]]$effect_sizes)) / as.numeric(pd[i])
}
tab <- do.call('rbind', tab)
# mash together positions with their CIs
tab$position <- paste(round(tab$ML_bayesint,1),
                      " (", round(tab$min_bayesint, 1), "-", round(tab$max_bayesint, 1), ")", sep="")
# print the table
kable(tab[,c("name", "site", "year","chr","position","LOD", "effect_sizes","PVE", "PDE")], digits = c(0,0,0,0,0,1,3,1),
      col.names = c("Name", "Site", "Year","Chr.","Position (cM)","LOD", "Effect size","% var. explained", "% diff. explained"),
      caption = "QTL for survival to reproduction identifed in individual experiments. QTL positions are shown with their 95% Bayesian credible intervals. Effect sizes are given as absolute values, as a percentage of variance among RIL means, and as a percentage of the difference between parental means.")

```

\newpage

```{r epistatic-qtl-table, eval=T}
epi_tab <- matrix(NA, nrow = 0, ncol=11)

for(tr in traits){
  for(sy in c("it2010", "it2011", "sw2010","sw2011")){
    eepi_tab <- grep(":", row.names(summary(qtlfits[[tr]][[sy]])$result.drop))
    this_summ <- summary(qtlfits[[tr]][[sy]])$result.drop[eepi_tab,]
    this_summ <- c(tr, substr(sy, 1,2), substr(sy, 3,6),
                   row.names(summary(qtlfits[[tr]][[sy]])$result.drop)[eepi_tab], this_summ)
    if(!all(this_summ %in% c(tr, substr(sy, 1,2), substr(sy, 3,6)))) epi_tab <- rbind(epi_tab, this_summ)
  }
}

epi_tab <- as.data.frame(epi_tab)
colnames(epi_tab)[1:4] <- c("Trait", "Site","Year", "QTL")
epi_tab <- epi_tab[, c("Trait", "Site","Year", "QTL", "LOD", "%var")]
# Comvert values from factors
epi_tab$Trait  <- as.vector(epi_tab$Trait)
epi_tab$LOD    <- as.numeric(as.vector(epi_tab$LOD))
epi_tab$`%var` <- as.numeric(as.vector(epi_tab$`%var`))

# Add prettier names
epi_tab$Trait[epi_tab$Trait == "seed"] <- "Seeds per fruit"
epi_tab$Trait[epi_tab$Trait == "tofu"] <- "Seeds per reproductive plant"
epi_tab$Trait[epi_tab$Trait == "tfit"] <- "Seeds per planted seedling"

epi_tab$Site <- ifelse(epi_tab$Site == "it", "Italy", "Sweden")

kable(epi_tab, digits = 2, row.names = F,
      col.names = c("Trait", "Site","Year", "QTL", "LOD", "% var. explained"),
      caption = "Pairs of significant epistatic QTL detected across traits.")
```

\newpage

```{r heritabilities, fig.cap="Broad-sense heritability estimates based on survival to reproduction, number of fruits per reproductive plant (Fruits/RP), number of seeds per fruit (Seeds/fr), number of fruits per seedling planted (Fruits/sdl), number of seeds per reproductive plant (Seeds/RP) and seed mass. Closed and open symbols show values in Italy and Sweden respectively. Error bars show 95% parametric bootstrap confidence intervals. Numbers indicate the number of individuals each estimate is based on."}

# pdf("figures/heritabilities.pdf", width=16.9/2.54, height = 12/2.54)
par(mfrow=c(1,2))

os <- 0.1
plot(
  c(1, 6),
  c(0, 0.6),
  type = "n",
  axes = F,
  xlim = c(0.2, 5.5),
  xlab = "",
  ylab = "Broad-sense heritability",
  main = "2010"
  )
axis(1, 1:5, las=2,
     labels = c("Survival", "Fruits/RP", "Seeds/fr", "Fruits/sdl", "Seed mass"))
axis(2)
box()
# Confidence intervals
segments((1:5) - os, H2$lower$`Italy 2010`,
         (1:5) - os, H2$upper$`Italy 2010`)
segments((1:5) + os, H2$lower$`Sweden 2010`,
         (1:5) + os, H2$upper$`Sweden 2010`)
# Overplot observed values
points((1:5) - os, H2$obs$`Italy 2010`,   pch=16)
points((1:5) + os, H2$obs$`Sweden 2010`, pch=21, bg="white")

# Add sample sizes
text((1:5) - 1.5*os, 0.6,
     labels = H2$n$`Italy 2010`,
     adj = 1,
     srt=90,
     cex=0.7)
text((1:5) + 1.5*os, 0.6,
     labels = H2$n$`Sweden 2010`,
     srt=90,
     adj=1,
     cex=0.7)

# 2011
plot(c(1, 5), c(0,0.6), type="n", axes = F, xlim= c(0.5, 5.5),
     xlab="", ylab="Broad-sense heritability", main="2011")
axis(1, 1:5, las=2,
     labels = c("Survival", "Fruits/RP", "Seeds/fr", "Fruits/sdl", "Seed mass"))
axis(2)
box()
# Confidence intervals
segments((1:5) - os, H2$lower$`Italy 2011`,
         (1:5) - os, H2$upper$`Italy 2011`)
segments((1:5) + os, H2$lower$`Sweden 2011`,
         (1:5) + os, H2$upper$`Sweden 2011`)
# Overplot observed values
points((1:5) - os, H2$obs$`Italy 2011`,   pch=16)
points((1:5) + os, H2$obs$`Sweden 2011`, pch=21, bg="white")

# Add sample sizes
text((1:5) - 1.5*os, 0.6,
     labels = H2$n$`Italy 2011`,
     adj = 1,
     srt=90,
     cex=0.7)
text((1:5) + 1.5*os, 0.6,
     labels = H2$n$`Sweden 2011`,
     srt=90,
     adj=1,
     cex=0.7)

# dev.off()
```


\newpage

```{r fig: epistatic-seed, fig.width=16.9/2.54, fig.height=10/2.54, cache=T, cache.lazy=T, fig.cap="Interaction plots for epistatic interactions detected for seed number per fruit, showing mean and standard errors for each genotype-by-genotype combination."}
# seed number per fruit
par(mfrow = c(1, 2))
effectplot(
  cross$seed,
  pheno.col = "it2011",
  mname1 = "1@5.3",
  mname2 = "5@15.0",
  add.legend = F,
  geno2 = c("It. allele", "Sw. allele"),
  main = "Italy 2011",
  xlab = "QTL 5@15.0",
  ylab = "Seed number per fruit"
)
legend(
  'topright',
  c("QTL 1@5.3", "It. allele", "Sw. allele"),
  col = c(0, 2, 4),
  pch = 1,
  bty = "n",
  cex = 0.8
)

effectplot(
  cross$seed,
  pheno.col = "sw2011",
  mname1 = "1@61.1",
  mname2 = "3@21.0",
  add.legend = F,
  geno2 = c("It. allele", "Sw. allele"),
  main = "Sweden 2011",
  xlab = "QTL 3@22.0",
  ylab = "Seed number per fruit"
)
legend(
  'topright',
  c("QTL 1@61.1", "It. allele", "Sw. allele"),
  col = c(0, 2, 4),
  pch = 1,
  bty = "n",
  cex = 0.8
)
```


```{r fig:epistatic-tofu, eval = T, fig.width = 9 / 2.54, fig.height = 10 /2.54, cache = T, cache.lazy = T, fig.cap = "Interaction plots for epistatic interactions detected for seed number per reproductive plant, showing mean and standard errors for each genotype-by-genotype combination."}

# seed number per plant
par(mfrow = c(1, 1))
effectplot(
  cross$tofu,
  pheno.col = "sw2011",
  mname1 = "1@61.1",
  mname2 = "3@24.4",
  add.legend = F,
  ylim = c(500, 1100),
  geno2 = c("It. allele", "Sw. allele"),
  main = "Sweden 2011",
  xlab = "QTL 3@24.4",
  ylab = "Seeds per reproductive plant"
)
legend(
  'bottomleft',
  c("QTL 1@61.1", "It. allele", "Sw. allele"),
  col = c(0, 2, 4),
  pch = 1,
  bty = "n",
  cex=0.8
)


```

```{r fig: epistatic-tfit, fig.width=9/2.54, fig.height=10/2.54, cache=T, cache.lazy=T, fig.cap="Interaction plots for epistatic interactions detected for seed number per planted seedling, showing mean and standard errors for each genotype-by-genotype combination."}
# seed number per plant
par(mfrow = c(1, 1))
effectplot(
  cross$tofu,
  pheno.col = "sw2011",
  mname1 = "1@61.1",
  mname2 = "3@18.0",
  add.legend = F,
  ylim = c(500, 1100),
  geno2 = c("It. allele", "Sw. allele"),
  main = "Sweden 2011",
  xlab = "QTL 3@18:0",
  ylab = "Seeds per reproductive plant"
)
legend('bottomleft', c("QTL 1@61.1", "It. allele", "Sw. allele"), col = c(0,2,4), pch=1, bty="n", cex=0.8)

```
