#' Tom Ellis
#' 
#' This script imports cross objects and QTL models from r/qtl and formats them
#' for further use:
#' 1. It concatenates cross and qtl objects for the same trait into a single list
#' 2. It runs `fitqtl` on each qtl object.
#' 3. It clusters QTL for each trait if their credible intervals overlap. 

library(arghqtl)
library(qtl)

# There are QTL models for each of four site-year combinations
siteyear <- c("it2010", "it2011", "sw2010", "sw2011")
# There are six phenotypes in each site-year combination:
traits <- c(
  "mass", # 1. seed mass (mass)
  "frut", # 2. fruits/plant ()
  "seed", # 3. seeds/fruit
  "tofu", # 4. Total fecundity (estimated seeds/plant = frut*seed)
  "ffit", # 5. Fruits per planted seedling
  "tfit", # 6. Seeds per planted seedling; fitness incorporating seed number.
  "surv") # 7. Survival
# parameters to input

# The following loop imports cross and qtl objects, then fits ANOVA models and clusters into groups.
# first, set up empty lists to hold this information.
cross <-              qtlmodels  <-       qtlfits  <- lapply(traits, function(x) return(NULL))
names(cross) <- names(qtlmodels) <- names(qtlfits) <- traits

for(i in traits){
  if (!file.exists(paste("data_derived/rqtl_", i,".csv",sep=""))){
    stop("R/QTL input file", paste("data_files/rqtl_", i,".csv",sep=""), " not found.
         This is generated by R/002.rqtl_files. Run that script first.")
  }
  # Import rqtl cross objects.
  thiscross <- read.cross("csv", "", paste("data_derived/rqtl_", i,".csv",sep=""),
                          na.strings=NA, genotypes = c("a", "b"), alleles=c("It","Sw"))
  thiscross <- convert2riself(thiscross)
  thiscross <-
    calc.genoprob(
      thiscross,
      step = 2,
      error.prob = .0001,
      map.function = "kosambi",
      stepwidth = "max",
      off.end = 0
    )
  cross[[i]] <- thiscross

  # import objects containing stepwise QTL fitting results.
  if(!file.exists(paste("output/stepwise_", i,".rds",sep=""))){
    stop("QTL model object ", paste("output/stepwise_", i, ".rds", sep="")," not found.
         This is generated by running ", paste("R/mapping_", i, ".R", sep=""),".")
  }
  thisqtl <- readRDS(paste("output/stepwise_", i, ".rds", sep=""))
  qtlmodels[[i]] <- thisqtl

  # fit ANOVAs to each QTL model
  thistrait <- lapply(siteyear, function(x) NULL)
  names(thistrait) <- siteyear
  # loop over individual years and get model fits for each
  for(y in siteyear) {
    # For survival in Sweden 2010, no QTL were identified. This if statement checks for that.
    if (length(thisqtl[[y]]) == 0) {
      thistrait[[y]] <- NA
    } else {
      thistrait[[y]] <-
        fitqtl(
          cross = thiscross,
          pheno.col = y,
          qtl = thisqtl[[y]],
          formula = formula(thisqtl[[y]]),
          method = "hk",
          model = "normal",
          covar = NULL,
          get.ests = T,
          dropone = T
        )
    }
  }
  qtlfits[[i]] <- thistrait
}

# Save output for supporting information so we don't need to repeat this.
saveRDS(cross,     file='output/cross_objects.rds')
saveRDS(qtlmodels, file='output/qtl_stepwise_models.rds')
saveRDS(qtlfits,   file='output/qtl_model_fits.rds')

# Cluster all QTL models as to identify pleiotropic regions.
# First we need to remove elements for survival in Sweden in 2010
qtlmodels2 <- qtlmodels[c("mass","frut","seed","surv")]
qtlfits2   <- qtlfits[c("mass","frut","seed","surv")]
qtlmodels2$surv <- qtlmodels2$surv[c("it2010", "it2011", "sw2011")]
qtlfits2$surv   <- qtlfits2$surv  [c("it2010", "it2011", "sw2011")]
# Flatten the first level of these lists, but keep object structure at lower levels
all_qtlmodels <- unlist(qtlmodels2, recursive = FALSE)
all_qtlfits   <- unlist(qtlfits2,   recursive = FALSE)
# Cluster all QTL models together
qtl_clusters <- cluster_qtl(1:5, all_qtlmodels, all_qtlfits, 15.2)
saveRDS(qtl_clusters, file="output/clusters_all_models.rds")
